import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "../components/layout/Header";
import SpotlightBackground from "../components/ui/SpotlightBackground";
import SmoothScroller from "../components/ui/SmoothScroller";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SmoothScroller />
        <SpotlightBackground />
        <Header />
        {children}
        <footer className="py-10 border-t border-white/5 text-center relative z-10">
          <p className="text-gray-500 text-sm">
            © {new Date().getFullYear()} KrouHub Servicios Digitales.
          </p>
        </footer>
      </body>
    </html>
  );
}
